---
title: "ACCORD Analysis"
date: "2024-03-25"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
library(openintro)
library(tidyverse)

expr1 <- read_csv("expr1/2024-10-9-16:40.csv")
expr2 <- read_csv("expr2/2024-10-15-22:22.csv")
summary(expr1)

expr1$std_dev <- apply(subset(expr1, select=c("dtime0","dtime1","dtime2","dtime3","dtime4","dtime5","dtime6","dtime7","dtime8","dtime9")), 1, sd)

expr2$log_file <- as.factor(expr2$log_file)
levels(expr2$log_file) <- c("Log 1", "Log 2", "Log 3", "Log 4")
log_files <- unique(expr2$log_file)
expr2.wider <- expr2 %>% select(!c("users","resources"))
expr2.wider <- expr2.wider %>% pivot_wider(id_cols=c(activity_count, selectivity_level), names_from=log_file, values_from=detection_time)
expr2.wider$avg_detection_time <- rowMeans(subset(expr2.wider, select = log_files))
expr2.wider$std_dev <- apply(subset(expr2.wider, select = log_files), 1, sd)

```

## Experiment 1: Construction Time
```{r, echo=FALSE}
expr1$std_dev
summary(expr1)
ggplot(data=expr1, aes(x=constraint_count, y=dtime_avg)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin=dtime_avg-std_dev, ymax=dtime_avg+std_dev)) +
  theme_bw() +
  labs(title="Construction time", x="Action constraints", y="Detection time (ms)")
```

## Experiment 2
### Graph
```{r, echo=FALSE}
ggplot(data=expr2.wider, aes(x=activity_count, y=avg_detection_time, group=selectivity_level, color=selectivity_level)) +
  geom_line(aes(linetype=selectivity_level))+
  scale_linetype_manual(values=c("dashed", "twodash", "solid"), breaks=c('low', 'medium', 'high'), labels=c("Low >=20%", "Medium >=5% and <20%", "High <5%")) +
  scale_color_discrete(breaks=c('low', 'medium', 'high'), labels=c("Low >=20%", "Medium >=5% and <20%", "High <5%")) +
  geom_point(show.legend=FALSE) +
  geom_errorbar(show.legend = FALSE, aes(ymin=avg_detection_time-std_dev, ymax=avg_detection_time+std_dev, width=25)) +
  theme_bw() +
  theme(legend.position="bottom", legend.title=element_blank()) +
  labs(title="Detection time by selectivity level", x="Activities", y="Detection time (ms)", color="Selectivity", linetype="Selectivity")


ggplot(data=expr2, aes(x=resources, y=detection_time, group=selectivity_level, color=selectivity_level)) +
  geom_point(aes(shape=log_file), breaks=c('low', 'medium', 'high'), labels=c("Low >=20%", "Medium >=5% and <20%", "High <5%")) +
  scale_color_discrete(breaks=c('low', 'medium', 'high'), labels=c("Low >=20%", "Medium >=5% and <20%", "High <5%")) +
  theme_bw() +
  # theme(legend.position="bottom", legend.title=element_blank()) +
  labs(title="Detection time vs. resources by selectivity level", x="Resources", y="Detection time (ms)", color="Selectivity", shape="Log file")

ggplot(data=expr2, aes(x=resources, y=detection_time, group=selectivity_level, color=selectivity_level)) +
  geom_point(breaks=c('low', 'medium', 'high'), labels=c("Low >=20%", "Medium >=5% and <20%", "High <5%")) +
  scale_color_discrete(breaks=c('low', 'medium', 'high'), labels=c("Low >=20%", "Medium >=5% and <20%", "High <5%")) +
  theme_bw() +
  theme(legend.position="bottom", legend.title=element_blank()) +
  labs(title="Detection time vs. resources by selectivity level", x="Resources", y="Detection time (ms)", color="Selectivity", shape="Log file")
```

### Stats
```{r, echo=FALSE}
ggplot(data=expr2, aes(x=selectivity_level, y=selectivity, fill=selectivity_level)) +
  geom_boxplot() +
  labs(title = "Variation of selectivity within a level", x = "Selectivity level", y = "Selectivity values")
```
Low
```{r, echo=FALSE}
expr2.low <- expr2 %>% filter(selectivity_level == "low")
expr2.low %>% summarise(mean = mean(selectivity),
            median = median(selectivity),
            std_dev = sd(selectivity),
            IQR = IQR(selectivity),
            min = min(selectivity),
            max = max(selectivity),
            var = var(selectivity),
            n = n())
```
Medium
```{r, echo=FALSE}
expr2.medium <- expr2 %>% filter(selectivity_level == "medium")
expr2.medium %>% summarise(mean = mean(selectivity),
            median = median(selectivity),
            std_dev = sd(selectivity),
            IQR = IQR(selectivity),
            min = min(selectivity),
            max = max(selectivity),
            var = var(selectivity),
            n = n())
```
High
```{r, echo=FALSE}
expr2.high <- expr2 %>% filter(selectivity_level == "high")
expr2.high %>% summarise(mean = mean(selectivity),
            median = median(selectivity),
            std_dev = sd(selectivity),
            IQR = IQR(selectivity),
            min = min(selectivity),
            max = max(selectivity),
            var = var(selectivity),
            n = n())

```